# Generated by Django 4.2.2 on 2023-06-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0003_todo_checked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="checked",
        ),
    ]
